
CREATE TABLE HANGHANGKHONG (
  MAHANG      VARCHAR2(5) PRIMARY KEY,
  TENHANG     NVARCHAR2(50),
  NGTL        DATE,
  DUONGBAY    NUMBER
);

CREATE TABLE CHUYENBAY (
  MACB        VARCHAR2(10) PRIMARY KEY,
  MAHANG      VARCHAR2(5),
  XUATPHAT    NVARCHAR2(50),
  DIEMDEN     NVARCHAR2(50),
  BATDAU      DATE,
  TGBAY       NUMBER,
  CONSTRAINT FK_CB_HANG
    FOREIGN KEY (MAHANG)
    REFERENCES HANGHANGKHONG(MAHANG)
);

CREATE TABLE NHANVIEN (
  MANV        VARCHAR2(5) PRIMARY KEY,
  HOTEN       NVARCHAR2(50),
  GIOITINH    NVARCHAR2(5),
  NGSINH      DATE,
  NGVL        DATE,
  CHUYENMON   NVARCHAR2(20),
  CONSTRAINT CK_CHUYENMON
    CHECK (CHUYENMON IN (N'Phi công', N'Tiếp viên'))
);

CREATE TABLE PHANCONG (
  MACB        VARCHAR2(10),
  MANV        VARCHAR2(5),
  NHIEMVU     NVARCHAR2(50),
  CONSTRAINT PK_PHANCONG PRIMARY KEY (MACB, MANV),
  CONSTRAINT FK_PC_CB FOREIGN KEY (MACB)
    REFERENCES CHUYENBAY(MACB),
  CONSTRAINT FK_PC_NV FOREIGN KEY (MANV)
    REFERENCES NHANVIEN(MANV)
);


INSERT INTO HANGHANGKHONG
VALUES ('VN', N'Vietnam Airlines', TO_DATE('15/01/1956','DD/MM/YYYY'), 52);

INSERT INTO HANGHANGKHONG
VALUES ('VJ', N'Vietjet Air', TO_DATE('25/12/2011','DD/MM/YYYY'), 33);

INSERT INTO HANGHANGKHONG
VALUES ('BL', N'Jetstar Pacific Airlines', TO_DATE('01/12/1990','DD/MM/YYYY'), 13);

INSERT INTO CHUYENBAY
VALUES ('VN550','VN',N'TP.HCM',N'Singapore',
        TO_DATE('20/12/2025','DD/MM/YYYY'),2);

INSERT INTO CHUYENBAY
VALUES ('VJ331','VJ',N'Đà Nẵng',N'Vinh',
        TO_DATE('28/12/2025','DD/MM/YYYY'),1);

INSERT INTO CHUYENBAY
VALUES ('BL696','BL',N'TP.HCM',N'Đà Lạt',
        TO_DATE('24/12/2025','DD/MM/YYYY'),0.5);

INSERT INTO NHANVIEN
VALUES ('NV01',N'Lâm Văn Bền',N'Nam',
        TO_DATE('10/09/1991','DD/MM/YYYY'),
        TO_DATE('05/06/2021','DD/MM/YYYY'),
        N'Phi công');

INSERT INTO NHANVIEN
VALUES ('NV02',N'Dương Thị Lục',N'Nữ',
        TO_DATE('22/03/1989','DD/MM/YYYY'),
        TO_DATE('12/11/2020','DD/MM/YYYY'),
        N'Tiếp viên');

INSERT INTO NHANVIEN
VALUES ('NV03',N'Hoàng Thanh Tùng',N'Nam',
        TO_DATE('29/07/1995','DD/MM/YYYY'),
        TO_DATE('11/04/2022','DD/MM/YYYY'),
        N'Tiếp viên');

INSERT INTO PHANCONG VALUES ('VN550','NV01',N'Cơ trưởng');
INSERT INTO PHANCONG VALUES ('VN550','NV02',N'Tiếp viên');
INSERT INTO PHANCONG VALUES ('BL696','NV03',N'Tiếp viên trưởng');

COMMIT;

PROMPT  CAU 5: NHAN VIEN SINH THANG 07 
SELECT *
FROM NHANVIEN
WHERE EXTRACT(MONTH FROM NGSINH) = 7;

PROMPT  CAU 6: CHUYEN BAY CO SO NHAN VIEN NHIEU NHAT 

SELECT MACB
FROM PHANCONG
GROUP BY MACB
HAVING COUNT(MANV) = (
  SELECT MAX(COUNT(MANV))
  FROM PHANCONG
  GROUP BY MACB
);

PROMPT CAU 7 
SELECT H.MAHANG, COUNT(DISTINCT C.MACB) AS SO_CHUYEN
FROM HANGHANGKHONG H
JOIN CHUYENBAY C ON H.MAHANG = C.MAHANG
LEFT JOIN PHANCONG P ON C.MACB = P.MACB
WHERE C.XUATPHAT = N'Đà Nẵng'
GROUP BY H.MAHANG, C.MACB
HAVING COUNT(P.MANV) < 2;

PROMPT CAU 8: NHAN VIEN THAM GIA TAT CA CHUYEN BAY
SELECT N.*
FROM NHANVIEN N
WHERE NOT EXISTS (
  SELECT *
  FROM CHUYENBAY C
  WHERE NOT EXISTS (
    SELECT *
    FROM PHANCONG P
    WHERE P.MACB = C.MACB
      AND P.MANV = N.MANV
  )
);


